// Autogenerated from java.template file

var mongoose = require('mongoose'), Schema = mongoose.Schema
var validate = require('mongoose-validator');

var nameValidator = [
  validate({
    validator: 'isLength',
    arguments: [2, 10],
    message: 'Name should be between {ARGS[0]} and {ARGS[1]} characters'
  }),
  validate({
    validator: 'isAlpha',
    passIfEmpty: true,
    message: 'Name should contain alpha-numeric characters only'
  })
];
var modelValidator = [
  validate({
    validator: 'isLength',
    arguments: [2, 5],
    message: 'Model should be between {ARGS[0]} and {ARGS[1]} characters'
  }),
];

var CarSchema = new mongoose.Schema({
  name:     {type:String, required: true
 , validate:nameValidator},  model:     {type:String, required: true
 , validate:modelValidator}})

module.exports = mongoose.model('CarSchema', CarSchema)