// Autogenerated from java.template file

var mongoose = require('mongoose'), Schema = mongoose.Schema
var validate = require('mongoose-validator');

var homeValidator = [
  validate({
    validator: 'isAlpha',
    passIfEmpty: true,
    message: 'Home should contain alpha-numeric characters only'
  })
];

var OwnerSchema = new mongoose.Schema({
  car:      {type:String, required: true
},  home:      {type:String, required: true
 , validate:homeValidator}})

module.exports = mongoose.model('OwnerSchema', OwnerSchema)