// Autogenerated from java.template file

var mongoose = require('mongoose'), Schema = mongoose.Schema
var validate = require('mongoose-validator');

var biographyValidator = [
  validate({
    validator: 'isLength',
    arguments: [3, 15],
    message: 'Biography should be between {ARGS[0]} and {ARGS[1]} characters'
  }),
  validate({
    validator: 'isAlpha',
    passIfEmpty: true,
    message: 'Biography should contain alpha-numeric characters only'
  })
];

var UserSchema = new mongoose.Schema({
  name:     {type:String, required: true
},  age:     {type:String, required: true
},  biography:     {type:String, required: true
 , validate:biographyValidator},  gender:     {type:String, required: true
}})

module.exports = mongoose.model('UserSchema', UserSchema)